services:
  api:
    container_name: api-node-container
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      HOST: 0.0.0.0
    volumes:
      - ./.env:/api/.env
      - ./package.json:/api/package.json
    ports:
      - "3000:3000"
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
